appName: codemida
hostName: codemida.com
environment: production
namespace: default

client:
  function: client
  appPort: 3000
  servicePort: 3000
  imageUrl: <ecr-client-image-url>
  pathPrefix: /
  resources:
    requests:
      cpu: 20m
      memory: 200Mi
    limits:
      cpu: 300m
      memory: 350Mi
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

api:
  function: api
  appPort: 8000
  servicePort: 8000
  secret: codemida-api-secret
  imageUrl: <ecr-api-image-url>
  pathPrefix: /api/v1/
  resources:
    requests:
      cpu: 10m
      memory: 150Mi
    limits:
      cpu: 200m
      memory: 300Mi
  hpa:
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
